# Generated by Django 5.1.7 on 2026-03-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_livro_autor_remove_livro_data_publicacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
